# Generated by Django 3.2.9 on 2021-11-16 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_updated_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date']},
        ),
    ]
