# Generated by Django 3.2.8 on 2021-12-09 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='aproved',
            new_name='approved',
        ),
    ]
